### ISSUE TITLE
AU Linux kernel 2016 запрос на проверку virt_mem_max Сташевский Леонид

### ISSUE THREAD

**Issue by e5l** [e5l/au-linux-kernel-spring-2016#3]
https://github.com/e5l/au-linux-kernel-spring-2016/commit/5095cffcc88ece369161853128bf7be6c55be9be

**Comment by eabatalov** [comment]
Your implementation doesn't allocate the maximal amount of memory because you allocate each available size only once. Suppose we have 10 non-continuous pages available in address space. You'll allocate only one.

You should /2 each size only once MAP_FAILED is returned for current size.
If kernel allows to allocate current size then you should continue to allocate it.

50 points out of 100.
